export type Lang = "de" | "en";

const de = {
  back: "Zurück",
  step: "Schritt",
  of: "von",
  startTitle: "Was ist dein Projekt wert?",
  startSub: "FairRate berechnet, ab welchem Preis sich deine Arbeit rechnet — und macht daraus drei Angebote, die du deiner Kundin erklären kannst.",
  start: "Los geht's",
  startNote: "etwa 5 Minuten · ohne Konto",
  howTitle: "So funktioniert's",
  howSteps: [
    ["Projekt beschreiben", "Drei kurze Fragen zu Beruf, Projektart und Umfang."],
    ["Kosten eintragen", "Wir fragen gezielt nach — auch nach dem, was man gern vergisst."],
    ["Untergrenze sehen", "Ab welchem Preis sich deine Arbeit wirklich rechnet."],
    ["Umfang festlegen", "Was zum Projekt gehört und was nicht."],
    ["Drei Angebote erhalten", "Basis, Empfohlen und Premium — fertig zum Versenden."],
  ],
  resultTitle: "Was du am Ende bekommst",
  professionTitle: "Was machst du beruflich?",
  professions: [
    ["Design", "UX/UI, Grafik, Produkt"],
    ["Entwicklung", "Web, App, IT"],
    ["Beratung", "Strategie, Marketing, Prozesse"],
    ["Coaching", "Einzel, Team, Training"],
    ["Text und Content", "Texte, Redaktion, Social"],
    ["Etwas anderes", ""],
    ["Handwerk und Produkte", "bald verfügbar"],
  ],
  projectTitle: "Welche Art von Projekt?",
  // Project types per profession, in the same order as `professions`.
  projectTypes: [
    ["Website", "App-Design", "Branding", "UX-Audit"],
    ["Website", "Web-App", "Mobile App", "Wartung"],
    ["Workshop", "Strategieprojekt", "Laufende Begleitung"],
    ["Einzelcoaching", "Gruppenprogramm", "Workshop"],
    ["Website-Texte", "Kampagne", "Content-Paket"],
  ],
  otherProject: "Projektart beschreiben",
  sizeTitle: "Wie groß ist das Projekt ungefähr?",
  sizes: ["Klein · bis 2 Wochen", "Mittel · 2 bis 6 Wochen", "Groß · über 6 Wochen"],
  estimateButton: "Schätzung ansehen",
  noNumbers: "Keine Zahlen abgefragt",
  estimate: "Schätzung",
  estimateValue: "3.900 – 5.100 €",
  standards: "mit Standardwerten berechnet",
  empty: "noch nicht ausgefüllt",
  emptyFields: ["Eigene Kosten", "Auslastung", "Leistungsumfang"],
  estimateExplain: "Mit deinen echten Kosten wird daraus deine persönliche Untergrenze.",
  refine: "Genauer machen",
  enough: "Reicht mir so",
  costsTitle: "Deine Kosten",
  costsSub: "Wir fragen gezielt nach — damit nichts untergeht.",
  costs: ["Software-Abos", "KI-Tools", "Steuerrücklage", "Urlaub und Ausfallzeiten", "Unbezahlte Akquisezeit", "Versicherungen", "Weiterbildung"],
  aiTip: "Und deine KI-Abos? Ein typischer Stack kostet 50–80 € im Monat.",
  privateNote: "Nur für diese Berechnung. Jederzeit änderbar und löschbar.",
  calculate: "Untergrenze berechnen",
  floorLabel: "DEINE UNTERGRENZE",
  floorSub: "Darunter rechnet sich deine Arbeit nicht.",
  why: "Warum dieser Preis?",
  whyRows: [["Fixkosten", "1.240 €"], ["Steuerrücklage", "620 €"], ["Marge", "780 €"]],
  assumptions: ["Auslastung", "Steuerrücklage", "Gewinnmarge"],
  defaults: ["Standardwert 75 %", "Standardwert 30 %", "Standardwert 20 %"],
  adjusted: "von dir angepasst",
  toScope: "Weiter zum Leistungsumfang",
  scopeTitle: "Was gehört zum Projekt?",
  scopeSub: "Erst danach wird gerechnet — so lässt sich dein Preis verteidigen.",
  services: "Leistungen",
  serviceItems: ["Konzept", "Design", "Entwicklung", "Texte", "SEO-Grundlagen"],
  revisions: "Korrekturschleifen",
  revisionItems: ["1", "2", "3", "unbegrenzt"],
  deadline: "Deadline",
  specifics: "Besonderheiten",
  specificItems: ["Eilauftrag", "Unklare Anforderungen", "Neue Kundin"],
  skip: "Überspringen",
  skipNote: "Dann wird dein Angebot als vorläufig markiert.",
  create: "Angebot erstellen",
  offersTitle: "Drei Angebotsoptionen",
  offersSub: "Jede Option hat einen eigenen Leistungsumfang.",
  options: ["Basis", "Empfohlen", "Premium"],
  optionScope: [
    ["3 Seiten", "2 Korrekturschleifen", "ohne Texte", "ohne Support"],
    ["5 Seiten", "3 Korrekturschleifen", "Text für die Startseite", "2 Wochen Support"],
    ["5 Seiten plus Buchung", "Korrekturen unbegrenzt", "alle Texte", "3 Monate Support"],
  ],
  excluded: "ohne",
  included: "Leistungsumfang ansehen",
  close: "Leistungsumfang schließen",
  offerNext: "Weiter zum Angebot",
  manual: "Preis manuell anpassen",
  adjustedScope: "Umfang angepasst · Entwicklung entfernt",
  priceTitle: "Preis anpassen",
  clientBudget: "Deine Kundin nennt ein Budget von 3.100 €.",
  yourOffer: "Dein Angebot",
  floorForScope: "Deine Untergrenze für diesen Umfang:",
  belowFloor: "{p} % unter deiner Untergrenze",
  warningText: "Bei diesem Preis bleibt nach Kosten und Steuer nichts übrig.",
  aboveFloor: "Über deiner Untergrenze",
  continuePrice: "Mit diesem Preis weiter",
  reduce: "Umfang reduzieren",
  anyway: "Trotzdem so anbieten",
  backOptions: "Zurück zu den Optionen",
  prepareTitle: "Dein Angebot",
  client: "Name der Kundin oder Firma",
  project: "Projekttitel",
  valid: "Gültig bis",
  message: "Persönliche Nachricht (optional)",
  offerNote: "Diese Angaben erscheinen nur im Angebot. Deine Kosten und deine Untergrenze werden nie angezeigt.",
  branding: "Branding",
  logo: "Logo hochladen",
  color: "Akzentfarbe wählen",
  docTitle: "ANGEBOT",
  next: "Weiter",
  sendTitle: "Angebot versenden",
  pdf: "PDF herunterladen",
  file: "Angebot_Kundin_Website.pdf",
  link: "Link kopieren",
  share: "fairrate.de/a/FR-4200",
  mail: "In E-Mail öffnen",
  sendNote: "FairRate verschickt nichts selbst. Du entscheidest, wann und wie dein Angebot rausgeht.",
  ready: "Angebot ist bereit",
  done: "Fertig",
  questions: "Wenn die Kundin nachfragt",
  situations: ["Rabattanfrage", "„Warum so teuer?“", "Budget ist kleiner", "Scope wurde größer", "Eilauftrag", "Absage unter Untergrenze"],
  replies: [
    "Gern passe ich den Umfang an — die Basis-Option liegt bei 3.000 €.",
    "Der Preis ergibt sich aus dem vereinbarten Umfang und der Zeit für ein hochwertiges Ergebnis.",
    "Wir können die wichtigsten Leistungen priorisieren und den Umfang entsprechend anpassen.",
    "Ich ergänze die neue Leistung transparent im Angebot und passe den Preis entsprechend an.",
    "Für die kürzere Vorlaufzeit plane ich Kapazität exklusiv für das Projekt ein.",
    "Danke für die Rückmeldung. Unter meiner Untergrenze kann ich das Projekt leider nicht wirtschaftlich umsetzen.",
  ],
  newOffer: "Neues Angebot",
  shortReady: "Deine erste Schätzung ist bereit. Du kannst jederzeit zurückkommen und sie mit deinen echten Kosten präzisieren.",
};

export type Texts = typeof de;

const en: Texts = {
  back: "Back",
  step: "Step",
  of: "of",
  startTitle: "What is your project worth?",
  startSub: "FairRate works out the price at which your work pays off — and turns it into three offers you can explain to your client.",
  start: "Let's go",
  startNote: "about 5 minutes · no account",
  howTitle: "How it works",
  howSteps: [
    ["Describe the project", "Three short questions on profession, project type and size."],
    ["Enter your costs", "We ask specifically — including what people tend to forget."],
    ["See your floor", "The price at which your work truly pays off."],
    ["Define the scope", "What is part of the project and what isn't."],
    ["Get three offers", "Basic, Recommended and Premium — ready to send."],
  ],
  resultTitle: "What you get in the end",
  professionTitle: "What do you do?",
  professions: [
    ["Design", "UX/UI, graphic, product"],
    ["Development", "Web, app, IT"],
    ["Consulting", "Strategy, marketing, processes"],
    ["Coaching", "Individual, team, training"],
    ["Copy and content", "Copy, editing, social"],
    ["Something else", ""],
    ["Crafts and products", "coming soon"],
  ],
  projectTitle: "What kind of project?",
  projectTypes: [
    ["Website", "App design", "Branding", "UX audit"],
    ["Website", "Web app", "Mobile app", "Maintenance"],
    ["Workshop", "Strategy project", "Ongoing support"],
    ["1:1 coaching", "Group programme", "Workshop"],
    ["Website copy", "Campaign", "Content package"],
  ],
  otherProject: "Describe the project type",
  sizeTitle: "Roughly how big is the project?",
  sizes: ["Small · up to 2 weeks", "Medium · 2 to 6 weeks", "Large · over 6 weeks"],
  estimateButton: "See estimate",
  noNumbers: "No numbers needed",
  estimate: "Estimate",
  estimateValue: "3.900 – 5.100 €",
  standards: "calculated with default values",
  empty: "not filled in yet",
  emptyFields: ["Your own costs", "Utilisation", "Scope"],
  estimateExplain: "With your real costs, this becomes your personal floor.",
  refine: "Make it precise",
  enough: "That's enough for me",
  costsTitle: "Your costs",
  costsSub: "We ask specifically — so nothing gets lost.",
  costs: ["Software subscriptions", "AI tools", "Tax reserve", "Holiday and downtime", "Unpaid acquisition time", "Insurance", "Training"],
  aiTip: "And your AI subscriptions? A typical stack costs 50–80 € a month.",
  privateNote: "Only used for this calculation. Can be changed or deleted anytime.",
  calculate: "Calculate floor",
  floorLabel: "YOUR PRICE FLOOR",
  floorSub: "Below this, your work does not pay off.",
  why: "Why this price?",
  whyRows: [["Fixed costs", "1.240 €"], ["Tax reserve", "620 €"], ["Margin", "780 €"]],
  assumptions: ["Utilisation", "Tax reserve", "Profit margin"],
  defaults: ["Default 75 %", "Default 30 %", "Default 20 %"],
  adjusted: "adjusted by you",
  toScope: "Continue to scope",
  scopeTitle: "What's part of the project?",
  scopeSub: "Only then do we calculate — so your price holds up.",
  services: "Deliverables",
  serviceItems: ["Concept", "Design", "Development", "Copy", "SEO basics"],
  revisions: "Revision rounds",
  revisionItems: ["1", "2", "3", "unlimited"],
  deadline: "Deadline",
  specifics: "Special factors",
  specificItems: ["Rush job", "Unclear requirements", "New client"],
  skip: "Skip",
  skipNote: "Your offer will then be marked as provisional.",
  create: "Create offer",
  offersTitle: "Three offer options",
  offersSub: "Each option has its own scope.",
  options: ["Basic", "Recommended", "Premium"],
  optionScope: [
    ["3 pages", "2 revision rounds", "without copy", "without support"],
    ["5 pages", "3 revision rounds", "Homepage copy", "2 weeks support"],
    ["5 pages plus booking", "Unlimited revisions", "All copy", "3 months support"],
  ],
  excluded: "without",
  included: "View scope",
  close: "Close scope",
  offerNext: "Continue to offer",
  manual: "Adjust price manually",
  adjustedScope: "Scope adjusted · development removed",
  priceTitle: "Adjust price",
  clientBudget: "Your client mentions a budget of 3.100 €.",
  yourOffer: "Your offer",
  floorForScope: "Your floor for this scope:",
  belowFloor: "{p} % below your price floor",
  warningText: "At this price nothing is left after costs and tax.",
  aboveFloor: "Above your price floor",
  continuePrice: "Continue with this price",
  reduce: "Reduce scope",
  anyway: "Offer it anyway",
  backOptions: "Back to options",
  prepareTitle: "Your offer",
  client: "Client or company name",
  project: "Project title",
  valid: "Valid until",
  message: "Personal message (optional)",
  offerNote: "These details only appear in the offer. Your costs and floor are never shown.",
  branding: "Branding",
  logo: "Upload logo",
  color: "Choose accent colour",
  docTitle: "OFFER",
  next: "Continue",
  sendTitle: "Send offer",
  pdf: "Download PDF",
  file: "Offer_Client_Website.pdf",
  link: "Copy link",
  share: "fairrate.de/a/FR-4200",
  mail: "Open in email",
  sendNote: "FairRate never sends anything itself. You decide when and how your offer goes out.",
  ready: "Your offer is ready",
  done: "Done",
  questions: "If your client asks",
  situations: ["Discount request", "“Why so expensive?”", "Budget is smaller", "Scope has grown", "Rush job", "Declining below floor"],
  replies: [
    "Happy to adjust the scope — the Basic option is 3.000 €.",
    "The price reflects the agreed scope and the time needed for a high-quality result.",
    "We can prioritise the most important deliverables and adjust the scope accordingly.",
    "I'll add the new deliverable to the offer transparently and adjust the price accordingly.",
    "For the shorter lead time I reserve capacity exclusively for this project.",
    "Thanks for getting back to me. Below my price floor I unfortunately can't deliver this project economically.",
  ],
  newOffer: "New offer",
  shortReady: "Your first estimate is ready. You can come back anytime and refine it with your real costs.",
};

export const texts: Record<Lang, Texts> = { de, en };
